/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hospitalmanagement;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Paint;
import java.sql.DriverManager;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.plot.PlotOrientation;


import java.sql.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;

import javax.swing.table.DefaultTableModel;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;

/**
 *
 * @author riyajoe07
 */
public class Doctor extends javax.swing.JFrame {
    Connection cn;
    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);

            headerLabel.setBackground(new Color(0, 102, 204)); // Blue
            headerLabel.setForeground(Color.WHITE);            // White text
            headerLabel.setFont(new Font("Rockwell", Font.PLAIN, 18));
            headerLabel.setHorizontalAlignment(SwingConstants.CENTER);
            headerLabel.setOpaque(true); // This makes background visible
            headerLabel.setBorder(BorderFactory.createLineBorder(Color.black));
            return headerLabel;
        }
    };

    JTableHeader header1 = doc_table.getTableHeader();
    for (int i = 0; i < doc_table.getColumnModel().getColumnCount(); i++) {
        doc_table.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
    }
    JTableHeader header12 = docav_table.getTableHeader();
    for (int i = 0; i < docav_table.getColumnModel().getColumnCount(); i++) {
        docav_table.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
    }
         try {
            Class.forName("oracle.jdbc.OracleDriver");
            System.out.println("Driver loaded");
            try {
                cn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1522/FREE", "system", "joevita");
                System.out.println("Connected to Oracle db");
            } catch (Exception p) {
                System.out.println(p.getMessage());
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toggle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        operations = new javax.swing.JPanel();
        insertb = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        statb = new javax.swing.JButton();
        deletb = new javax.swing.JButton();
        viewb = new javax.swing.JButton();
        deletep = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        doc_idtd = new javax.swing.JTextField();
        doc_delete = new javax.swing.JButton();
        mainp = new javax.swing.JPanel();
        insertp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        doc_idti = new javax.swing.JTextField();
        doc_nameti = new javax.swing.JTextField();
        doc_conti = new javax.swing.JTextField();
        dep_docidi = new javax.swing.JTextField();
        doc_insert = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        doc_datei = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        doc_timeti = new javax.swing.JTextField();
        doc_statusti = new javax.swing.JComboBox<>();
        updatep = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        doc_idtu = new javax.swing.JTextField();
        doc_nametu = new javax.swing.JTextField();
        doc_dateu = new javax.swing.JTextField();
        dep_docidu = new javax.swing.JTextField();
        doc_update = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        doc_contu1 = new javax.swing.JTextField();
        doc_timetu = new javax.swing.JTextField();
        doc_statustu = new javax.swing.JComboBox<>();
        viewp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doc_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        docav_table = new javax.swing.JTable();
        statp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        sidePanel = new javax.swing.JPanel();
        homen = new javax.swing.JButton();
        patn = new javax.swing.JButton();
        nursen = new javax.swing.JButton();
        recepn = new javax.swing.JButton();
        billn = new javax.swing.JButton();
        roomn = new javax.swing.JButton();
        medicinen = new javax.swing.JButton();
        admn = new javax.swing.JButton();
        appn = new javax.swing.JButton();
        servicen = new javax.swing.JButton();
        presn = new javax.swing.JButton();
        deptn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1061, 50));

        toggle.setBackground(new java.awt.Color(204, 204, 255));
        toggle.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\menui.png")); // NOI18N
        toggle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toggle.setBorderPainted(false);
        toggle.setContentAreaFilled(false);
        toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel1.setText("NOVA HEAL");

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\logouti.png")); // NOI18N
        logout.setText("logout");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\doctori.png")); // NOI18N
        jLabel2.setText("Doctor MODULE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(toggle)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(188, 188, 188)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(logout)
                        .addComponent(jLabel2))
                    .addComponent(toggle))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 70));

        operations.setBackground(new java.awt.Color(153, 153, 255));
        operations.setBorder(new javax.swing.border.MatteBorder(null));

        insertb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        insertb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\inserti.png")); // NOI18N
        insertb.setText("Insert");
        insertb.setBorderPainted(false);
        insertb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbActionPerformed(evt);
            }
        });

        updateb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        updateb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-update-64.png")); // NOI18N
        updateb.setText("Update");
        updateb.setBorderPainted(false);
        updateb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        statb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        statb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-statistics-64.png")); // NOI18N
        statb.setText("Statistics");
        statb.setBorderPainted(false);
        statb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        statb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbActionPerformed(evt);
            }
        });

        deletb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        deletb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-delete-64.png")); // NOI18N
        deletb.setText("Delete");
        deletb.setBorderPainted(false);
        deletb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deletb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deletb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbActionPerformed(evt);
            }
        });

        viewb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        viewb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-view-64.png")); // NOI18N
        viewb.setText("View");
        viewb.setBorderPainted(false);
        viewb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbActionPerformed(evt);
            }
        });

        deletep.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel11.setText("Doctor Id");

        doc_idtd.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        doc_delete.setBackground(new java.awt.Color(204, 204, 255));
        doc_delete.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        doc_delete.setText("Delete");
        doc_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletepLayout = new javax.swing.GroupLayout(deletep);
        deletep.setLayout(deletepLayout);
        deletepLayout.setHorizontalGroup(
            deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepLayout.createSequentialGroup()
                .addGroup(deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletepLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(doc_idtd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deletepLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(doc_delete)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        deletepLayout.setVerticalGroup(
            deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(doc_idtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(doc_delete)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(insertb)
                .addGap(75, 75, 75)
                .addComponent(deletb)
                .addGap(68, 68, 68)
                .addComponent(updateb)
                .addGap(70, 70, 70)
                .addComponent(viewb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statb)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deletep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(deletep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(operations, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 820, 110));

        mainp.setLayout(new java.awt.CardLayout());

        insertp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("Doctor Id");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel8.setText("Doctor Name");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setText("Doctor Contact");

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel10.setText("Department Id");

        doc_idti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        doc_idti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_idtiActionPerformed(evt);
            }
        });

        doc_nameti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        doc_nameti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_nametiActionPerformed(evt);
            }
        });

        doc_conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_contiActionPerformed(evt);
            }
        });

        dep_docidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_docidiActionPerformed(evt);
            }
        });

        doc_insert.setBackground(new java.awt.Color(204, 204, 255));
        doc_insert.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        doc_insert.setText("Insert");
        doc_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_insertActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel16.setText("Available Time");

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel17.setText("Available Date");

        doc_datei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_dateiActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel18.setText("Availability Status");

        doc_timeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_timetiActionPerformed(evt);
            }
        });

        doc_statusti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        doc_statusti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Booked" }));

        javax.swing.GroupLayout insertpLayout = new javax.swing.GroupLayout(insertp);
        insertp.setLayout(insertpLayout);
        insertpLayout.setHorizontalGroup(
            insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertpLayout.createSequentialGroup()
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertpLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(insertpLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(doc_datei, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertpLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doc_conti, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertpLayout.createSequentialGroup()
                                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(insertpLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(doc_nameti, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(doc_idti)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertpLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                        .addComponent(dep_docidi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertpLayout.createSequentialGroup()
                                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doc_timeti, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(doc_statusti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(insertpLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(doc_insert)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        insertpLayout.setVerticalGroup(
            insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_idti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_nameti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dep_docidi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_conti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_datei, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_timeti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_statusti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(doc_insert)
                .addGap(38, 38, 38))
        );

        mainp.add(insertp, "card2");

        updatep.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel12.setText("Doctor Id");

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel13.setText("Doctor Name");

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel14.setText("Doctor Contact");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel15.setText("Department Id");

        doc_idtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_idtuActionPerformed(evt);
            }
        });

        doc_nametu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_nametuActionPerformed(evt);
            }
        });

        doc_update.setBackground(new java.awt.Color(204, 204, 255));
        doc_update.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        doc_update.setText("Update");
        doc_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_updateActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel19.setText("Available Time");

        jLabel20.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel20.setText("Available Date");

        jLabel21.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel21.setText("Availability Status");

        doc_statustu.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        doc_statustu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Booked" }));

        javax.swing.GroupLayout updatepLayout = new javax.swing.GroupLayout(updatep);
        updatep.setLayout(updatepLayout);
        updatepLayout.setHorizontalGroup(
            updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepLayout.createSequentialGroup()
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatepLayout.createSequentialGroup()
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatepLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel15))
                                    .addGroup(updatepLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel12))
                                    .addGroup(updatepLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel13))
                                    .addGroup(updatepLayout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel14))))
                                .addGap(245, 245, 245))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addGap(224, 224, 224)))
                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dep_docidu, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(doc_nametu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doc_idtu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doc_dateu)
                            .addComponent(doc_timetu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doc_contu1)
                            .addComponent(doc_statustu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(doc_update)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        updatepLayout.setVerticalGroup(
            updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updatepLayout.createSequentialGroup()
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(doc_idtu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(doc_nametu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(dep_docidu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(doc_contu1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(doc_dateu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel19))
                            .addComponent(doc_timetu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(doc_statustu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21))
                .addGap(31, 31, 31)
                .addComponent(doc_update)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        mainp.add(updatep, "card4");

        viewp.setBackground(new java.awt.Color(255, 255, 255));

        doc_table.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        doc_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "D_Id", "D_Name", "De_Id", "D_Contact"
            }
        ));
        doc_table.setRowHeight(25);
        doc_table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        doc_table.setShowHorizontalLines(true);
        doc_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(doc_table);

        docav_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "D_Id", "Avail_date", "Avail_Time", "Status"
            }
        ));
        docav_table.setRowHeight(25);
        docav_table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        docav_table.setShowHorizontalLines(true);
        docav_table.setShowVerticalLines(true);
        jScrollPane2.setViewportView(docav_table);

        javax.swing.GroupLayout viewpLayout = new javax.swing.GroupLayout(viewp);
        viewp.setLayout(viewpLayout);
        viewpLayout.setHorizontalGroup(
            viewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewpLayout.setVerticalGroup(
            viewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewpLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(viewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainp.add(viewp, "card5");

        statp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Doctor Id");

        jLabel4.setText("Doctor Name");

        jLabel5.setText("Department Id");

        jLabel6.setText("Doctor Contact");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statpLayout = new javax.swing.GroupLayout(statp);
        statp.setLayout(statpLayout);
        statpLayout.setHorizontalGroup(
            statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statpLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(157, 157, 157)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        statpLayout.setVerticalGroup(
            statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statpLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        mainp.add(statp, "card6");

        getContentPane().add(mainp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 820, 450));

        sidePanel.setBackground(new java.awt.Color(204, 204, 204));

        homen.setBackground(new java.awt.Color(204, 204, 204));
        homen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        homen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\homei.png")); // NOI18N
        homen.setText("Home");
        homen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homen.setBorderPainted(false);
        homen.setContentAreaFilled(false);
        homen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        homen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homenActionPerformed(evt);
            }
        });

        patn.setBackground(new java.awt.Color(204, 204, 204));
        patn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        patn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\patienti.png")); // NOI18N
        patn.setText("Patient");
        patn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        patn.setBorderPainted(false);
        patn.setContentAreaFilled(false);
        patn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patnActionPerformed(evt);
            }
        });

        nursen.setBackground(new java.awt.Color(204, 204, 204));
        nursen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        nursen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\nursei.png")); // NOI18N
        nursen.setText("Nurse");
        nursen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nursen.setBorderPainted(false);
        nursen.setContentAreaFilled(false);
        nursen.setDefaultCapable(false);
        nursen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursenActionPerformed(evt);
            }
        });

        recepn.setBackground(new java.awt.Color(204, 204, 204));
        recepn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        recepn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\recepi.png")); // NOI18N
        recepn.setText("Receptionist");
        recepn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        recepn.setBorderPainted(false);
        recepn.setContentAreaFilled(false);
        recepn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepnActionPerformed(evt);
            }
        });

        billn.setBackground(new java.awt.Color(204, 204, 204));
        billn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        billn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\billi.png")); // NOI18N
        billn.setText("Bill");
        billn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        billn.setBorderPainted(false);
        billn.setContentAreaFilled(false);
        billn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnActionPerformed(evt);
            }
        });

        roomn.setBackground(new java.awt.Color(204, 204, 204));
        roomn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        roomn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\roomi.png")); // NOI18N
        roomn.setText("Room");
        roomn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        roomn.setBorderPainted(false);
        roomn.setContentAreaFilled(false);
        roomn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnActionPerformed(evt);
            }
        });

        medicinen.setBackground(new java.awt.Color(204, 204, 204));
        medicinen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        medicinen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\medi.png")); // NOI18N
        medicinen.setText("Medicine");
        medicinen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        medicinen.setBorderPainted(false);
        medicinen.setContentAreaFilled(false);
        medicinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinenActionPerformed(evt);
            }
        });

        admn.setBackground(new java.awt.Color(204, 204, 204));
        admn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        admn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\admit.png")); // NOI18N
        admn.setText("Admission");
        admn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        admn.setBorderPainted(false);
        admn.setContentAreaFilled(false);
        admn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnActionPerformed(evt);
            }
        });

        appn.setBackground(new java.awt.Color(204, 204, 204));
        appn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        appn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\appi.png")); // NOI18N
        appn.setText("Appointment");
        appn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        appn.setBorderPainted(false);
        appn.setContentAreaFilled(false);
        appn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appnActionPerformed(evt);
            }
        });

        servicen.setBackground(new java.awt.Color(204, 204, 204));
        servicen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        servicen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\servicei.png")); // NOI18N
        servicen.setText("Nursing Service");
        servicen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        servicen.setBorderPainted(false);
        servicen.setContentAreaFilled(false);
        servicen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicenActionPerformed(evt);
            }
        });

        presn.setBackground(new java.awt.Color(204, 204, 204));
        presn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        presn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\presi.png")); // NOI18N
        presn.setText("Prescription");
        presn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        presn.setBorderPainted(false);
        presn.setContentAreaFilled(false);
        presn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presnActionPerformed(evt);
            }
        });

        deptn.setBackground(new java.awt.Color(204, 204, 204));
        deptn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        deptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\depti.png")); // NOI18N
        deptn.setText("Department");
        deptn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deptn.setBorderPainted(false);
        deptn.setContentAreaFilled(false);
        deptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nursen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recepn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicinen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(patn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homen)
                .addGap(18, 18, 18)
                .addComponent(deptn)
                .addGap(18, 18, 18)
                .addComponent(nursen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patn)
                .addGap(24, 24, 24)
                .addComponent(recepn)
                .addGap(18, 18, 18)
                .addComponent(billn)
                .addGap(18, 18, 18)
                .addComponent(roomn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicinen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admn)
                .addGap(18, 18, 18)
                .addComponent(appn)
                .addGap(18, 18, 18)
                .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(presn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void slideSidePanel(boolean show) {
    new Thread(() -> {
        int width = sidePanel.getWidth();
        int step = 10;
        int delay = 5;

        if (show) {
            for (int i = 0; i <= width; i += step) {
                sidePanel.setSize(i, sidePanel.getHeight());
                try { Thread.sleep(delay); } catch (InterruptedException e) {}
            }
        } else {
            for (int i = width; i >= 0; i -= step) {
                sidePanel.setSize(i, sidePanel.getHeight());
                try { Thread.sleep(delay); } catch (InterruptedException e) {}
            }
        }
        sidePanel.setVisible(show);
    }).start();
    
}
    
    
    private boolean isSidePanelVisible = true;
    private void toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleActionPerformed
        // TODO add your handling code here:

        isSidePanelVisible = !isSidePanelVisible;  // Toggle state
        slideSidePanel(isSidePanelVisible);

    }//GEN-LAST:event_toggleActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void insertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(insertp);
        mainp.repaint();
        mainp.revalidate();
    }//GEN-LAST:event_insertbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(updatep);
        mainp.repaint();
        mainp.revalidate();
    }//GEN-LAST:event_updatebActionPerformed

    private void statbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbActionPerformed
        // TODO add your handling code here:
       
        try{
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
         // Your DB connection method
        String sql = "SELECT De_id, COUNT(*) AS doctor_count FROM Doctor GROUP BY De_id";
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            int deptId = rs.getInt("De_id");
            int count = rs.getInt("doctor_count");
            dataset.addValue(count, "Doctors", "Dept " + deptId);
        }

        // Step 2: Create the chart
        JFreeChart barChart = ChartFactory.createBarChart(
                "Doctors per Department",
                "Department ID",
                "Number of Doctors",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        Color[] barColors = {
    new Color(255, 99, 132),   // red
    new Color(54, 162, 235),   // blue
    new Color(255, 206, 86),   // yellow
    new Color(75, 192, 192),   // teal
    new Color(153, 102, 255),  // purple
    new Color(255, 159, 64),   // orange
};

BarRenderer renderer = new BarRenderer() {
    @Override
    public Paint getItemPaint(int row, int column) {
        return barColors[column % barColors.length];
    }
};

CategoryPlot plot = barChart.getCategoryPlot();
plot.setRenderer(renderer);

// Optional: gridline and background customization
plot.setBackgroundPaint(Color.WHITE);
plot.setRangeGridlinePaint(Color.DARK_GRAY);
        // Step 3: Create ChartPanel
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        chartPanel.setMouseWheelEnabled(true);

        // Step 4: Clear and update statp panel
        statp.removeAll();
        statp.setLayout(new java.awt.BorderLayout());
        statp.add(chartPanel, java.awt.BorderLayout.CENTER);
        statp.revalidate();
        statp.repaint();

        // Step 5: Show statp in mainp
        mainp.removeAll();
        mainp.add(statp);
        mainp.revalidate();
        mainp.repaint();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, "Error displaying chart: " + e.getMessage());
        }
        
    }//GEN-LAST:event_statbActionPerformed

    private void deletbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbActionPerformed
        mainp.removeAll();
        mainp.add(deletep);
        mainp.repaint();
        mainp.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_deletbActionPerformed

    private void viewbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(viewp);
        mainp.repaint();
        mainp.revalidate();
        try{
            Statement st1 = cn.createStatement();
            Statement st2 = cn.createStatement();
            String sql1 = "Select * from Doctor";
            String sql2 = "Select * from Doctor_Schedule";
            ResultSet rs1 = st1.executeQuery(sql1);
            ResultSet rs2 = st2.executeQuery(sql2);
            DefaultTableModel tblModel1 = (DefaultTableModel)doc_table.getModel();
            DefaultTableModel tblModel2 = (DefaultTableModel)docav_table.getModel();
            tblModel1.setRowCount(0);
             tblModel2.setRowCount(0);
             SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

            while(rs1.next())
            {
                String d_id = String.valueOf(rs1.getInt("d_id"));
                String d_name = rs1.getString("d_name");
                String de_id = String.valueOf(rs1.getInt("de_id"));
                String d_contact =rs1.getString("d_contact");
                
                
                tblModel1.addRow(new Object[]{d_id,d_name,de_id,d_contact});
            }
            
              while(rs2.next())
            {
                String d_id = String.valueOf(rs2.getInt("d_id"));
                String av_date = sdf.format(rs2.getDate("avail_date"));
                String av_time= rs2.getString("avail_time");
                String av_stat =rs2.getString("status");
                
                
                tblModel2.addRow(new Object[]{d_id,av_date,av_time,av_stat});
            }


        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }

    }//GEN-LAST:event_viewbActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void doc_idtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_idtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_idtiActionPerformed

    private void doc_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_insertActionPerformed
        // TODO add your handling code here:
        int doc_id = Integer.parseInt(doc_idti.getText());
        String dept_name = doc_nameti.getText();
        String doc_contact = doc_conti.getText();
        int dept_id = Integer.parseInt(dep_docidi.getText());
        String av_date = doc_datei.getText();
        String av_time = doc_timeti.getText();
        String av_status = doc_statusti.getSelectedItem().toString();
        
       SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        
        String sql1 = "insert into Doctor values(?,?,?,?)";
        String sql2 = "insert into Doctor_Schedule values(?,?,?,?)";
        try{
        java.util.Date utildate1 = sdf.parse(av_date); 
         
        java.sql.Date sqldate1 = new java.sql.Date(utildate1.getTime());
        
        PreparedStatement ps1 = cn.prepareStatement(sql1);
        PreparedStatement ps2 = cn.prepareStatement(sql2);
        ps1.setInt(1,doc_id);
        ps1.setString(2,dept_name);
        ps1.setInt(3,dept_id);
        ps1.setString(4,doc_contact);
        ps2.setInt(1,doc_id);
        ps2.setDate(2,sqldate1);
        ps2.setString(3,av_time);
        ps2.setString(4,av_status);
        int rows1 = ps1.executeUpdate();
        int rows2 = ps2.executeUpdate();
        if(rows1>0)
        {
            JOptionPane.showMessageDialog(null,"Inserted value in Doctor");
            if(rows2>0)
           {
               JOptionPane.showMessageDialog(null,"Inserted value in Doctor Schedule");
           }
            else{
            JOptionPane.showMessageDialog(null,"Insertion failed in Doctor Schedule");
            }
        }
        else{
        JOptionPane.showMessageDialog(null,"Insertion failed in Doctor");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_doc_insertActionPerformed

    private void doc_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_deleteActionPerformed
        // TODO add your handling code here:
        int doc_id = Integer.parseInt(doc_idtd.getText());
       
        String sql = "delete from Doctor where D_id = ?";
        try{
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setInt(1,doc_id);
        
        int rows = ps.executeUpdate();
        if(rows>0)
        {
        JOptionPane.showMessageDialog(null,"Deleted value in Doctor and Doctor Schedule");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Deletion failed in Doctor and Doctor Schedule");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_doc_deleteActionPerformed

    private void dep_docidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_docidiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_docidiActionPerformed

    private void doc_contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_contiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_contiActionPerformed

    private void doc_nametiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_nametiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_nametiActionPerformed

    private void doc_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_updateActionPerformed
        int doc_id = Integer.parseInt(doc_idtu.getText());
        String doc_name = doc_nametu.getText();
        int dept_id = Integer.parseInt(dep_docidu.getText());
        String doc_contact = doc_dateu.getText();
        String av_date = doc_dateu.getText();
        String av_time = doc_timetu.getText();
        String av_status = doc_statustu.getSelectedItem().toString();
        
       SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        String sql1 = "update Doctor set D_name = ?,De_id = ?,D_contact = ? where D_id = ?";
        String sql2 = "update Doctor_Schedule set status = ? where d_id = ? and avail_date=? and avail_time=?";
        try{
        java.util.Date utildate1 = sdf.parse(av_date); 
         
        java.sql.Date sqldate1 = new java.sql.Date(utildate1.getTime());
        PreparedStatement ps1 = cn.prepareStatement(sql1);
        PreparedStatement ps2 = cn.prepareStatement(sql2);
        ps1.setString(1,doc_name);
        ps1.setInt(2,dept_id);
        ps1.setString(3,doc_contact);
        ps1.setInt(4, doc_id);
        ps2.setString(1,av_status);
        ps2.setInt(2,doc_id);
        ps2.setDate(3,sqldate1);
        ps2.setString(4,av_time);

        int rows1 = ps1.executeUpdate();
        int rows2 = ps2.executeUpdate();
        if(rows1>0)
        {
        JOptionPane.showMessageDialog(null,"Updated value in Doctor");
        if(rows2>0)
           {
               JOptionPane.showMessageDialog(null,"Updated value in Doctor Schedule");
           }
            else{
            JOptionPane.showMessageDialog(null,"Updation failed in Doctor Schedule");
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Updation failed in Doctor");
         
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_doc_updateActionPerformed

    private void doc_dateiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_dateiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_dateiActionPerformed

    private void doc_timetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_timetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_timetiActionPerformed

    private void doc_idtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_idtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_idtuActionPerformed

    private void doc_nametuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_nametuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_nametuActionPerformed

    private void homenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homenActionPerformed
        // TODO add your handling code here:
        welcome welcomeFrame = new welcome();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homenActionPerformed

    private void patnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patnActionPerformed
        // TODO add your handling code here:
        Patient welcomeFrame = new Patient();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_patnActionPerformed

    private void nursenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursenActionPerformed
        // TODO add your handling code here:
        Nurse welcomeFrame = new Nurse();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_nursenActionPerformed

    private void recepnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepnActionPerformed
        // TODO add your handling code here:
        Receptionist welcomeFrame = new Receptionist();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_recepnActionPerformed

    private void billnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnActionPerformed
        // TODO add your handling code here:
        Bill welcomeFrame = new Bill();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billnActionPerformed

    private void roomnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnActionPerformed
        // TODO add your handling code here:
        Room welcomeFrame = new Room();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_roomnActionPerformed

    private void medicinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinenActionPerformed
        Medicine welcomeFrame = new Medicine();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_medicinenActionPerformed

    private void admnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnActionPerformed
        // TODO add your handling code here:
        Admission welcomeFrame = new Admission();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_admnActionPerformed

    private void appnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appnActionPerformed
        // TODO add your handling code here:
        Appointment welcomeFrame = new Appointment();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_appnActionPerformed

    private void servicenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicenActionPerformed
        Nursing_Service welcomeFrame = new Nursing_Service();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_servicenActionPerformed

    private void presnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presnActionPerformed
        // TODO add your handling code here:
        Prescription welcomeFrame = new Prescription();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_presnActionPerformed

    private void deptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptnActionPerformed
        // TODO add your handling code here:
        Department deptFrame = new Department();
        deptFrame.setVisible(true);
        deptFrame.pack();
        deptFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_deptnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admn;
    private javax.swing.JButton appn;
    private javax.swing.JButton billn;
    private javax.swing.JButton deletb;
    private javax.swing.JPanel deletep;
    private javax.swing.JTextField dep_docidi;
    private javax.swing.JTextField dep_docidu;
    private javax.swing.JButton deptn;
    private javax.swing.JTextField doc_conti;
    private javax.swing.JTextField doc_contu1;
    private javax.swing.JTextField doc_datei;
    private javax.swing.JTextField doc_dateu;
    private javax.swing.JButton doc_delete;
    private javax.swing.JTextField doc_idtd;
    private javax.swing.JTextField doc_idti;
    private javax.swing.JTextField doc_idtu;
    private javax.swing.JButton doc_insert;
    private javax.swing.JTextField doc_nameti;
    private javax.swing.JTextField doc_nametu;
    private javax.swing.JComboBox<String> doc_statusti;
    private javax.swing.JComboBox<String> doc_statustu;
    private javax.swing.JTable doc_table;
    private javax.swing.JTextField doc_timeti;
    private javax.swing.JTextField doc_timetu;
    private javax.swing.JButton doc_update;
    private javax.swing.JTable docav_table;
    private javax.swing.JButton homen;
    private javax.swing.JButton insertb;
    private javax.swing.JPanel insertp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainp;
    private javax.swing.JButton medicinen;
    private javax.swing.JButton nursen;
    private javax.swing.JPanel operations;
    private javax.swing.JButton patn;
    private javax.swing.JButton presn;
    private javax.swing.JButton recepn;
    private javax.swing.JButton roomn;
    private javax.swing.JButton servicen;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton statb;
    private javax.swing.JPanel statp;
    private javax.swing.JButton toggle;
    private javax.swing.JButton updateb;
    private javax.swing.JPanel updatep;
    private javax.swing.JButton viewb;
    private javax.swing.JPanel viewp;
    // End of variables declaration//GEN-END:variables
}
