/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hospitalmanagement;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.DriverManager;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

import java.sql.*;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riyajoe07
 */
public class Receptionist extends javax.swing.JFrame {
    Connection cn;

    /**
     * Creates new form Receptionist
     */
    public Receptionist() {
        initComponents();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);

            headerLabel.setBackground(new Color(0, 102, 204)); // Blue
            headerLabel.setForeground(Color.WHITE);            // White text
            headerLabel.setFont(new Font("Rockwell", Font.PLAIN, 18));
            headerLabel.setHorizontalAlignment(SwingConstants.CENTER);
            headerLabel.setOpaque(true); // This makes background visible
            headerLabel.setBorder(BorderFactory.createLineBorder(Color.black));
            return headerLabel;
        }
    };

    JTableHeader header = recep_table.getTableHeader();
    for (int i = 0; i < recep_table.getColumnModel().getColumnCount(); i++) {
        recep_table.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
    }
    try {
            Class.forName("oracle.jdbc.OracleDriver");
            System.out.println("Driver loaded");
            try {
                cn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1522/FREE", "system", "joevita");
                System.out.println("Connected to Oracle db");
            } catch (Exception p) {
                System.out.println(p.getMessage());
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toggle = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        mainp = new javax.swing.JPanel();
        insertp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        recep_idti = new javax.swing.JTextField();
        recep_nameti = new javax.swing.JTextField();
        recep_conti = new javax.swing.JTextField();
        recep_insert = new javax.swing.JButton();
        deletep = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        recep_idtd = new javax.swing.JTextField();
        recep_delete = new javax.swing.JButton();
        updatep = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        recep_idtu = new javax.swing.JTextField();
        recep_nametu = new javax.swing.JTextField();
        recep_contu = new javax.swing.JTextField();
        recep_update = new javax.swing.JButton();
        viewp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recep_table = new javax.swing.JTable();
        statp = new javax.swing.JPanel();
        operations = new javax.swing.JPanel();
        insertb = new javax.swing.JButton();
        deletb = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        viewb = new javax.swing.JButton();
        statb = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        homen = new javax.swing.JButton();
        patn = new javax.swing.JButton();
        docn = new javax.swing.JButton();
        nursen = new javax.swing.JButton();
        billn = new javax.swing.JButton();
        roomn = new javax.swing.JButton();
        medicinen = new javax.swing.JButton();
        admn = new javax.swing.JButton();
        appn = new javax.swing.JButton();
        servicen = new javax.swing.JButton();
        presn = new javax.swing.JButton();
        deptn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigp.setBackground(new java.awt.Color(204, 204, 255));
        navigp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        navigp.setPreferredSize(new java.awt.Dimension(1061, 50));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel1.setText("NOVA HEAL");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\recepi.png")); // NOI18N
        jLabel2.setText("RECEPTIONIST MODULE");

        toggle.setBackground(new java.awt.Color(204, 204, 255));
        toggle.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\menui.png")); // NOI18N
        toggle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toggle.setBorderPainted(false);
        toggle.setContentAreaFilled(false);
        toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\logouti.png")); // NOI18N
        logout.setText("logout");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigpLayout = new javax.swing.GroupLayout(navigp);
        navigp.setLayout(navigpLayout);
        navigpLayout.setHorizontalGroup(
            navigpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(toggle)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(31, 31, 31))
        );
        navigpLayout.setVerticalGroup(
            navigpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigpLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(navigpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggle)
                    .addGroup(navigpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        getContentPane().add(navigp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 60));

        mainp.setLayout(new java.awt.CardLayout());

        insertp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Receptionist Id");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setText("Receptionist Name");

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel5.setText("Receptionist Contact");

        recep_idti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        recep_idti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_idtiActionPerformed(evt);
            }
        });

        recep_nameti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        recep_conti.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        recep_insert.setBackground(new java.awt.Color(204, 204, 255));
        recep_insert.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        recep_insert.setText("Insert");
        recep_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertpLayout = new javax.swing.GroupLayout(insertp);
        insertp.setLayout(insertpLayout);
        insertpLayout.setHorizontalGroup(
            insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertpLayout.createSequentialGroup()
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertpLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(insertpLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(95, 95, 95)
                                .addComponent(recep_conti, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(insertpLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recep_nameti, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(insertpLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(142, 142, 142)
                                    .addComponent(recep_idti, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(insertpLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(recep_insert)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        insertpLayout.setVerticalGroup(
            insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertpLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(insertpLayout.createSequentialGroup()
                        .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(recep_idti, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(recep_nameti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(insertpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(recep_conti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(recep_insert)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        mainp.add(insertp, "card2");

        deletep.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setText("Receptionist Id");

        recep_idtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_idtdActionPerformed(evt);
            }
        });

        recep_delete.setBackground(new java.awt.Color(204, 204, 255));
        recep_delete.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        recep_delete.setText("Delete");
        recep_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletepLayout = new javax.swing.GroupLayout(deletep);
        deletep.setLayout(deletepLayout);
        deletepLayout.setHorizontalGroup(
            deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepLayout.createSequentialGroup()
                .addGroup(deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletepLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel6)
                        .addGap(179, 179, 179)
                        .addComponent(recep_idtd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deletepLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(recep_delete)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        deletepLayout.setVerticalGroup(
            deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(recep_idtd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(recep_delete)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        mainp.add(deletep, "card3");

        updatep.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("Receptionist Id");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel8.setText("Receptionist Name");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setText("Receptionist Contact");

        recep_contu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_contuActionPerformed(evt);
            }
        });

        recep_update.setBackground(new java.awt.Color(204, 204, 255));
        recep_update.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        recep_update.setText("Update");
        recep_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatepLayout = new javax.swing.GroupLayout(updatep);
        updatep.setLayout(updatepLayout);
        updatepLayout.setHorizontalGroup(
            updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepLayout.createSequentialGroup()
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(130, 130, 130)
                        .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(recep_contu, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(recep_nametu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recep_idtu, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(recep_update)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        updatepLayout.setVerticalGroup(
            updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(recep_idtu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatepLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recep_nametu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(updatepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(recep_contu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(recep_update)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        mainp.add(updatep, "card4");

        viewp.setBackground(new java.awt.Color(255, 255, 255));

        recep_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Re_Id", "Re_Name", "Re_Contact"
            }
        ));
        recep_table.setRowHeight(25);
        recep_table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        recep_table.setShowHorizontalLines(true);
        recep_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(recep_table);

        javax.swing.GroupLayout viewpLayout = new javax.swing.GroupLayout(viewp);
        viewp.setLayout(viewpLayout);
        viewpLayout.setHorizontalGroup(
            viewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        viewpLayout.setVerticalGroup(
            viewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        mainp.add(viewp, "card5");

        statp.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout statpLayout = new javax.swing.GroupLayout(statp);
        statp.setLayout(statpLayout);
        statpLayout.setHorizontalGroup(
            statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        statpLayout.setVerticalGroup(
            statpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        mainp.add(statp, "card6");

        getContentPane().add(mainp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 850, 490));

        operations.setBackground(new java.awt.Color(153, 153, 255));
        operations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        operations.setPreferredSize(new java.awt.Dimension(819, 120));

        insertb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        insertb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\inserti.png")); // NOI18N
        insertb.setText("Insert");
        insertb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbActionPerformed(evt);
            }
        });

        deletb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        deletb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-delete-64.png")); // NOI18N
        deletb.setText("Delete");
        deletb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deletb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deletb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbActionPerformed(evt);
            }
        });

        updateb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        updateb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-update-64.png")); // NOI18N
        updateb.setText("Update");
        updateb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        viewb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        viewb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-view-64.png")); // NOI18N
        viewb.setText("View");
        viewb.setBorderPainted(false);
        viewb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbActionPerformed(evt);
            }
        });

        statb.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        statb.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\icons8-statistics-64.png")); // NOI18N
        statb.setText("Statistics");
        statb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        statb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(insertb)
                .addGap(76, 76, 76)
                .addComponent(deletb)
                .addGap(67, 67, 67)
                .addComponent(updateb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(viewb)
                .addGap(66, 66, 66)
                .addComponent(statb)
                .addGap(59, 59, 59))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(operations, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 850, 120));

        sidePanel.setBackground(new java.awt.Color(204, 204, 204));

        homen.setBackground(new java.awt.Color(204, 204, 204));
        homen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        homen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\homei.png")); // NOI18N
        homen.setText("Home");
        homen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homen.setBorderPainted(false);
        homen.setContentAreaFilled(false);
        homen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        homen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homenActionPerformed(evt);
            }
        });

        patn.setBackground(new java.awt.Color(204, 204, 204));
        patn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        patn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\patienti.png")); // NOI18N
        patn.setText("Patient");
        patn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        patn.setBorderPainted(false);
        patn.setContentAreaFilled(false);
        patn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patnActionPerformed(evt);
            }
        });

        docn.setBackground(new java.awt.Color(204, 204, 204));
        docn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        docn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\doctori.png")); // NOI18N
        docn.setText("Doctor");
        docn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        docn.setBorderPainted(false);
        docn.setContentAreaFilled(false);
        docn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docnActionPerformed(evt);
            }
        });

        nursen.setBackground(new java.awt.Color(204, 204, 204));
        nursen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        nursen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\nursei.png")); // NOI18N
        nursen.setText("Nurse");
        nursen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nursen.setBorderPainted(false);
        nursen.setContentAreaFilled(false);
        nursen.setDefaultCapable(false);
        nursen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursenActionPerformed(evt);
            }
        });

        billn.setBackground(new java.awt.Color(204, 204, 204));
        billn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        billn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\billi.png")); // NOI18N
        billn.setText("Bill");
        billn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        billn.setBorderPainted(false);
        billn.setContentAreaFilled(false);
        billn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnActionPerformed(evt);
            }
        });

        roomn.setBackground(new java.awt.Color(204, 204, 204));
        roomn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        roomn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\roomi.png")); // NOI18N
        roomn.setText("Room");
        roomn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        roomn.setBorderPainted(false);
        roomn.setContentAreaFilled(false);
        roomn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnActionPerformed(evt);
            }
        });

        medicinen.setBackground(new java.awt.Color(204, 204, 204));
        medicinen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        medicinen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\medi.png")); // NOI18N
        medicinen.setText("Medicine");
        medicinen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        medicinen.setBorderPainted(false);
        medicinen.setContentAreaFilled(false);
        medicinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinenActionPerformed(evt);
            }
        });

        admn.setBackground(new java.awt.Color(204, 204, 204));
        admn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        admn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\admit.png")); // NOI18N
        admn.setText("Admission");
        admn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        admn.setBorderPainted(false);
        admn.setContentAreaFilled(false);
        admn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnActionPerformed(evt);
            }
        });

        appn.setBackground(new java.awt.Color(204, 204, 204));
        appn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        appn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\appi.png")); // NOI18N
        appn.setText("Appointment");
        appn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        appn.setBorderPainted(false);
        appn.setContentAreaFilled(false);
        appn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appnActionPerformed(evt);
            }
        });

        servicen.setBackground(new java.awt.Color(204, 204, 204));
        servicen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        servicen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\servicei.png")); // NOI18N
        servicen.setText("Nursing Service");
        servicen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        servicen.setBorderPainted(false);
        servicen.setContentAreaFilled(false);
        servicen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicenActionPerformed(evt);
            }
        });

        presn.setBackground(new java.awt.Color(204, 204, 204));
        presn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        presn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\presi.png")); // NOI18N
        presn.setText("Prescription");
        presn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        presn.setBorderPainted(false);
        presn.setContentAreaFilled(false);
        presn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presnActionPerformed(evt);
            }
        });

        deptn.setBackground(new java.awt.Color(204, 204, 204));
        deptn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        deptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\depti.png")); // NOI18N
        deptn.setText("Department");
        deptn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deptn.setBorderPainted(false);
        deptn.setContentAreaFilled(false);
        deptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nursen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicinen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(patn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homen)
                .addGap(21, 21, 21)
                .addComponent(deptn)
                .addGap(18, 18, 18)
                .addComponent(docn)
                .addGap(18, 18, 18)
                .addComponent(nursen)
                .addGap(18, 18, 18)
                .addComponent(patn)
                .addGap(18, 18, 18)
                .addComponent(billn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicinen)
                .addGap(18, 18, 18)
                .addComponent(admn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appn)
                .addGap(18, 18, 18)
                .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(presn)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void slideSidePanel(boolean show) {
    new Thread(() -> {
        int width = sidePanel.getWidth();
        int step = 10;
        int delay = 5;

        if (show) {
            for (int i = 0; i <= width; i += step) {
                sidePanel.setSize(i, sidePanel.getHeight());
                try { Thread.sleep(delay); } catch (InterruptedException e) {}
            }
        } else {
            for (int i = width; i >= 0; i -= step) {
                sidePanel.setSize(i, sidePanel.getHeight());
                try { Thread.sleep(delay); } catch (InterruptedException e) {}
            }
        }
        sidePanel.setVisible(show);
    }).start();
    
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   

        

      

      

       // </editor-fold>                        
 private boolean isSidePanelVisible = true;
    private void toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleActionPerformed
        // TODO add your handling code here:

        isSidePanelVisible = !isSidePanelVisible;  // Toggle state
        slideSidePanel(isSidePanelVisible);

    }//GEN-LAST:event_toggleActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void recep_idtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_idtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recep_idtdActionPerformed

    private void recep_contuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_contuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recep_contuActionPerformed

    private void insertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(insertp);
        mainp.repaint();
        mainp.revalidate();
    }//GEN-LAST:event_insertbActionPerformed

    private void deletbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbActionPerformed
        mainp.removeAll();
        mainp.add(deletep);
        mainp.repaint();
        mainp.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_deletbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(updatep);
        mainp.repaint();
        mainp.revalidate();
    }//GEN-LAST:event_updatebActionPerformed

    private void viewbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(viewp);
        mainp.repaint();
        mainp.revalidate();
        try{
            Statement st = cn.createStatement();
            String sql = "Select * from Receptionist";
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel tblModel = (DefaultTableModel)recep_table.getModel();
            tblModel.setRowCount(0);

            while(rs.next())
            {
                String re_id = String.valueOf(rs.getInt("Re_id"));
                String re_name = rs.getString("Re_name");
                
                String re_contact =rs.getString("Re_contact");

                tblModel.addRow(new Object[]{re_id,re_name,re_contact});
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_viewbActionPerformed

    private void statbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbActionPerformed
        // TODO add your handling code here:
        mainp.removeAll();
        mainp.add(statp);
        mainp.repaint();
        mainp.revalidate();
    }//GEN-LAST:event_statbActionPerformed

    private void recep_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_insertActionPerformed
        // TODO add your handling code here:
        int recep_id = Integer.parseInt(recep_idti.getText());
        String recep_name = recep_nameti.getText();
        String recep_cont = recep_conti.getText();
        String sql = "insert into Receptionist values(?,?,?)";
        try{
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setInt(1,recep_id);
        ps.setString(2,recep_name);
        ps.setString(3,recep_cont);
        int rows = ps.executeUpdate();
        if(rows>0)
        {
            JOptionPane.showMessageDialog(null,"Inserted value in Receptionist");
        }
        else{
        JOptionPane.showMessageDialog(null,"Insertion failed in Receptionist");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_recep_insertActionPerformed

    private void recep_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_deleteActionPerformed
        // TODO add your handling code here:
        int recep_id = Integer.parseInt(recep_idtd.getText());
       
        String sql = "delete from Receptionist where Re_id = ?";
        try{
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setInt(1,recep_id);
        
        int rows = ps.executeUpdate();
        if(rows>0)
        {
        JOptionPane.showMessageDialog(null,"Deleted value in Receptionist");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Deletion failed in Receptionist");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_recep_deleteActionPerformed

    private void recep_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_updateActionPerformed
        // TODO add your handling code here:
        int recep_id = Integer.parseInt(recep_idtu.getText());
        String recep_name = recep_nametu.getText();
        String recep_cont = recep_contu.getText();
        String sql = "update Receptionist set Re_name = ?,Re_contact = ? where Re_id = ?";
        try{
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1,recep_name);
        ps.setString(2,recep_cont);
        ps.setInt(3,recep_id);
        int rows = ps.executeUpdate();
        if(rows>0)
        {
            JOptionPane.showMessageDialog(null,"Updated value in Receptionist");
        }
        else{
        JOptionPane.showMessageDialog(null,"Updation failed in Receptionist");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_recep_updateActionPerformed

    private void recep_idtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_idtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recep_idtiActionPerformed

    private void homenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homenActionPerformed
        // TODO add your handling code here:
        welcome welcomeFrame = new welcome();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homenActionPerformed

    private void patnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patnActionPerformed
        // TODO add your handling code here:
        Patient welcomeFrame = new Patient();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_patnActionPerformed

    private void docnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docnActionPerformed
        // TODO add your handling code here:
        Doctor welcomeFrame = new Doctor();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_docnActionPerformed

    private void nursenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursenActionPerformed
        // TODO add your handling code here:
        Nurse welcomeFrame = new Nurse();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_nursenActionPerformed

    private void billnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnActionPerformed
        // TODO add your handling code here:
        Bill welcomeFrame = new Bill();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billnActionPerformed

    private void roomnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnActionPerformed
        // TODO add your handling code here:
        Room welcomeFrame = new Room();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_roomnActionPerformed

    private void medicinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinenActionPerformed
        Medicine welcomeFrame = new Medicine();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_medicinenActionPerformed

    private void admnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnActionPerformed
        // TODO add your handling code here:
        Admission welcomeFrame = new Admission();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_admnActionPerformed

    private void appnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appnActionPerformed
        // TODO add your handling code here:
        Appointment welcomeFrame = new Appointment();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_appnActionPerformed

    private void servicenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicenActionPerformed
        Nursing_Service welcomeFrame = new Nursing_Service();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_servicenActionPerformed

    private void presnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presnActionPerformed
        // TODO add your handling code here:
        Prescription welcomeFrame = new Prescription();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_presnActionPerformed

    private void deptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptnActionPerformed
        // TODO add your handling code here:
        Department deptFrame = new Department();
        deptFrame.setVisible(true);
        deptFrame.pack();
        deptFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_deptnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admn;
    private javax.swing.JButton appn;
    private javax.swing.JButton billn;
    private javax.swing.JButton deletb;
    private javax.swing.JPanel deletep;
    private javax.swing.JButton deptn;
    private javax.swing.JButton docn;
    private javax.swing.JButton homen;
    private javax.swing.JButton insertb;
    private javax.swing.JPanel insertp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainp;
    private javax.swing.JButton medicinen;
    private javax.swing.JPanel navigp;
    private javax.swing.JButton nursen;
    private javax.swing.JPanel operations;
    private javax.swing.JButton patn;
    private javax.swing.JButton presn;
    private javax.swing.JTextField recep_conti;
    private javax.swing.JTextField recep_contu;
    private javax.swing.JButton recep_delete;
    private javax.swing.JTextField recep_idtd;
    private javax.swing.JTextField recep_idti;
    private javax.swing.JTextField recep_idtu;
    private javax.swing.JButton recep_insert;
    private javax.swing.JTextField recep_nameti;
    private javax.swing.JTextField recep_nametu;
    private javax.swing.JTable recep_table;
    private javax.swing.JButton recep_update;
    private javax.swing.JButton roomn;
    private javax.swing.JButton servicen;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton statb;
    private javax.swing.JPanel statp;
    private javax.swing.JButton toggle;
    private javax.swing.JButton updateb;
    private javax.swing.JPanel updatep;
    private javax.swing.JButton viewb;
    private javax.swing.JPanel viewp;
    // End of variables declaration//GEN-END:variables
}
