/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hospitalmanagement;

/**
 *
 * @author riyajoe07
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        homen = new javax.swing.JButton();
        patn = new javax.swing.JButton();
        docn = new javax.swing.JButton();
        nursen = new javax.swing.JButton();
        recepn = new javax.swing.JButton();
        billn = new javax.swing.JButton();
        roomn = new javax.swing.JButton();
        medicinen = new javax.swing.JButton();
        admn = new javax.swing.JButton();
        appn = new javax.swing.JButton();
        servicen = new javax.swing.JButton();
        presn = new javax.swing.JButton();
        deptn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel1.setText("    Nova Heal");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\useri.png")); // NOI18N
        jLabel2.setText("Welcome User");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\menui.png")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\back.jpg")); // NOI18N
        jLabel12.setText("Welcome to Nova Heal. Your Health Our Mission");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 780, 630));

        sidePanel.setBackground(new java.awt.Color(204, 204, 204));

        homen.setBackground(new java.awt.Color(204, 204, 204));
        homen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        homen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\homei.png")); // NOI18N
        homen.setText("Home");
        homen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homen.setBorderPainted(false);
        homen.setContentAreaFilled(false);
        homen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        homen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homenActionPerformed(evt);
            }
        });

        patn.setBackground(new java.awt.Color(204, 204, 204));
        patn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        patn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\patienti.png")); // NOI18N
        patn.setText("Patient");
        patn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        patn.setBorderPainted(false);
        patn.setContentAreaFilled(false);
        patn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patnActionPerformed(evt);
            }
        });

        docn.setBackground(new java.awt.Color(204, 204, 204));
        docn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        docn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\doctori.png")); // NOI18N
        docn.setText("Doctor");
        docn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        docn.setBorderPainted(false);
        docn.setContentAreaFilled(false);
        docn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docnActionPerformed(evt);
            }
        });

        nursen.setBackground(new java.awt.Color(204, 204, 204));
        nursen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        nursen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\nursei.png")); // NOI18N
        nursen.setText("Nurse");
        nursen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nursen.setBorderPainted(false);
        nursen.setContentAreaFilled(false);
        nursen.setDefaultCapable(false);
        nursen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nursenActionPerformed(evt);
            }
        });

        recepn.setBackground(new java.awt.Color(204, 204, 204));
        recepn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        recepn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\recepi.png")); // NOI18N
        recepn.setText("Receptionist");
        recepn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        recepn.setBorderPainted(false);
        recepn.setContentAreaFilled(false);
        recepn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepnActionPerformed(evt);
            }
        });

        billn.setBackground(new java.awt.Color(204, 204, 204));
        billn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        billn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\billi.png")); // NOI18N
        billn.setText("Bill");
        billn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        billn.setBorderPainted(false);
        billn.setContentAreaFilled(false);
        billn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnActionPerformed(evt);
            }
        });

        roomn.setBackground(new java.awt.Color(204, 204, 204));
        roomn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        roomn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\roomi.png")); // NOI18N
        roomn.setText("Room");
        roomn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        roomn.setBorderPainted(false);
        roomn.setContentAreaFilled(false);
        roomn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnActionPerformed(evt);
            }
        });

        medicinen.setBackground(new java.awt.Color(204, 204, 204));
        medicinen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        medicinen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\medi.png")); // NOI18N
        medicinen.setText("Medicine");
        medicinen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        medicinen.setBorderPainted(false);
        medicinen.setContentAreaFilled(false);
        medicinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinenActionPerformed(evt);
            }
        });

        admn.setBackground(new java.awt.Color(204, 204, 204));
        admn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        admn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\admit.png")); // NOI18N
        admn.setText("Admission");
        admn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        admn.setBorderPainted(false);
        admn.setContentAreaFilled(false);
        admn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnActionPerformed(evt);
            }
        });

        appn.setBackground(new java.awt.Color(204, 204, 204));
        appn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        appn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\appi.png")); // NOI18N
        appn.setText("Appointment");
        appn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        appn.setBorderPainted(false);
        appn.setContentAreaFilled(false);
        appn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appnActionPerformed(evt);
            }
        });

        servicen.setBackground(new java.awt.Color(204, 204, 204));
        servicen.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        servicen.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\servicei.png")); // NOI18N
        servicen.setText("Nursing Service");
        servicen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        servicen.setBorderPainted(false);
        servicen.setContentAreaFilled(false);
        servicen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicenActionPerformed(evt);
            }
        });

        presn.setBackground(new java.awt.Color(204, 204, 204));
        presn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        presn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\presi.png")); // NOI18N
        presn.setText("Prescription");
        presn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        presn.setBorderPainted(false);
        presn.setContentAreaFilled(false);
        presn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presnActionPerformed(evt);
            }
        });

        deptn.setBackground(new java.awt.Color(204, 204, 204));
        deptn.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        deptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\evija\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagement\\src\\main\\java\\com\\mycompany\\hospitalmanagement\\icons\\depti.png")); // NOI18N
        deptn.setText("Department");
        deptn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deptn.setBorderPainted(false);
        deptn.setContentAreaFilled(false);
        deptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nursen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recepn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicinen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homen)
                .addGap(21, 21, 21)
                .addComponent(deptn)
                .addGap(18, 18, 18)
                .addComponent(docn)
                .addGap(18, 18, 18)
                .addComponent(nursen)
                .addGap(18, 18, 18)
                .addComponent(patn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recepn)
                .addGap(18, 18, 18)
                .addComponent(billn)
                .addGap(18, 18, 18)
                .addComponent(roomn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicinen)
                .addGap(18, 18, 18)
                .addComponent(admn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(servicen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presn)
                .addGap(51, 51, 51))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homenActionPerformed
        // TODO add your handling code here:
        welcome welcomeFrame = new welcome();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homenActionPerformed

    private void patnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patnActionPerformed
        // TODO add your handling code here:
        Patient welcomeFrame = new Patient();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_patnActionPerformed

    private void docnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docnActionPerformed
        // TODO add your handling code here:
         Doctor welcomeFrame = new Doctor();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_docnActionPerformed

    private void recepnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepnActionPerformed
        // TODO add your handling code here:
        Receptionist welcomeFrame = new Receptionist();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_recepnActionPerformed

    private void billnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnActionPerformed
        // TODO add your handling code here:
        Bill welcomeFrame = new Bill();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billnActionPerformed

    private void roomnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnActionPerformed
        // TODO add your handling code here:
        Room welcomeFrame = new Room();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_roomnActionPerformed

    private void medicinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinenActionPerformed
         Medicine welcomeFrame = new Medicine();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_medicinenActionPerformed

    private void admnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnActionPerformed
        // TODO add your handling code here:
        Admission welcomeFrame = new Admission();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_admnActionPerformed

    private void servicenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicenActionPerformed
        Nursing_Service welcomeFrame = new Nursing_Service();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_servicenActionPerformed

    private void presnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presnActionPerformed
        // TODO add your handling code here:
        Prescription welcomeFrame = new Prescription();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_presnActionPerformed

    private void deptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptnActionPerformed
        // TODO add your handling code here:
        Department deptFrame = new Department();
        deptFrame.setVisible(true);
        deptFrame.pack();
        deptFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_deptnActionPerformed

    private void nursenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nursenActionPerformed
        // TODO add your handling code here:
         Nurse welcomeFrame = new Nurse();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_nursenActionPerformed

    private void appnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appnActionPerformed
        // TODO add your handling code here:
        Appointment welcomeFrame = new Appointment();
        welcomeFrame.setVisible(true);
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_appnActionPerformed

    /**
     * @param args the command line arguments
     */
    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admn;
    private javax.swing.JButton appn;
    private javax.swing.JButton billn;
    private javax.swing.JButton deptn;
    private javax.swing.JButton docn;
    private javax.swing.JButton homen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medicinen;
    private javax.swing.JButton nursen;
    private javax.swing.JButton patn;
    private javax.swing.JButton presn;
    private javax.swing.JButton recepn;
    private javax.swing.JButton roomn;
    private javax.swing.JButton servicen;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
